blank_issues_enabled: false
contact_links:
  - name: "⛔ Question"
    url: https://kws-computer.de/produkte-2/bridgeth/
    about: "Please do not use GitHub for asking questions. If you simply have a question, then the BridgEth Base Homepage are the best place to ask it. Thanks in advance for helping us keep the issue tracker clean!"
